config/routes.rb
Rails.application.routes.draw do

namespace :admin do
  resources :sessions, only: [:new, :create, :destroy]
  resources :admin, only: :show
  resources :venues
  resources :tradeshows 

  root to: "sessions#new"
end

  get "public/index"

  root to: "public#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  validates :username, presence: true


  has_secure_password
end

app/models/booth.rb
class Booth < ActiveRecord::Base
  belongs_to :tradeshow
end

app/models/tradeshow.rb
class Tradeshow < ActiveRecord::Base
  #Associations

  has_many :booths
  belongs_to :venue

  #CallBacks
  before_create :associated_venue

  #Nested Associations
  accepts_nested_attributes_for :booths

  #Methods

#need to rework so there isn't default db writing unless accurate
  def associated_venue

    tradeshow_venue = Venue.find_or_create_by(name: self.venue_name) do |venue|
      venue.address = self.location
    end

    self.venue = tradeshow_venue
  end

  def self.search(search)
    where("title LIKE ? OR location LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  #Associations
  has_many :tradeshows

  #Callbacks
  geocoded_by :address
  after_create :geocode_address

  #Scopes
  scope :has_address, -> {Venue.where.not(latitude: nil, longitude: nil)}
  scope :no_address,  -> {Venue.where(latitude: nil, longitude: nil)}

  #Methods
  
  def geocode_address
    begin
      geocode
    rescue => e
Rails.logger.info(e)
    end
  end


end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < Admin::ApplicationController
  def show
    @disable_search = true
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    Admin.find_by(id: session[:admin_id])
  end

  def require_sign_in
    unless current_user
      flash[:error] = "You must be logged in to do that"
      redirect_to new_admin_session_path
    end
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController

  def new
    @disable_search = true
  end

  def create
    admin = Admin.find_by(username: params[:session][:username].downcase)
    if admin && admin.authenticate(params[:session][:password])
      create_session(admin)
      flash[:notice] = "Welcome back"
      redirect_to admin_admin_path(admin)
    else
      flash.now[:alert] = "invalid email/password combination"
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "Successfully signed out."
    redirect_to root_path
  end

private

  def create_session(admin)
    session[:admin_id] = admin.id
  end

  def destroy_session(admin)
    session[:admin_id] = nil
  end

  def current_user
    Admin.find_by(id: session[:admin_id])
  end


end

app/controllers/admin/tradeshows_controller.rb
class Admin::TradeshowsController < Admin::ApplicationController
  def index
    @tradeshows = Tradeshow.all
    @disable_search = true
  end

  def show
    @tradeshow = Tradeshow.find(params[:id])
    @disable_search = true
  end

  def new
    @tradeshow = Tradeshow.new
    @tradeshow.booths.build
    @disable_search = true
  end

  def create
    @tradeshow = Tradeshow.create(tradeshow_params)

    if @tradeshow.save
      flash[:notice] = "Record was created successfully."
      redirect_to admin_tradeshow_path(@tradeshow)
    else
      flash[:error] = "There was an error creating the record. Please try again."
      render new
    end
  end

  def edit
    @tradeshow = Tradeshow.find(params[:id])
    @disable_search = true
  end

  def update
    @tradeshow = Tradeshow.find(params[:id])
    @tradeshow.update_attributes(tradeshow_params)


    if @tradeshow.save
      flash[:notice] = "Tradeshow updated."
      redirect_to admin_tradeshow_path(@tradeshow)
    else
      flash[:error] = "There was an error saving the changes. Please try again."
      render :edit
    end

  end


  def destroy
    @tradeshow = Tradeshow.find(params[:id])

    if @tradeshow.destroy
      flash[:notice] = "\"#{@tradeshow.title}\" was deleted successfully."
      redirect_to admin_tradeshows_path
    else
      flash[:error] = "There was an error deleting the Tradeshow."
      render :show
    end
  end

  private

  def tradeshow_params
    params.require(:tradeshow).permit(:title, :description, :location, :date, :venue_name, booths_attributes: :size)
  end


end

app/controllers/admin/venues_controller.rb
class Admin::VenuesController < Admin::ApplicationController
  def index
    @venues = Venue.all
    @disable_search = true
  end

  def show
    @venue = Venue.find(params[:id])
    @disable_search = true
  end

  def new
    @venue = Venue.new
    @disable_search = true
  end

  def create
    @venue = Venue.create(venue_params)
    if @venue.save
      flash[:notice] = "Record was created successfully."
      redirect_to admin_venue_path(@venue)
    else
      flash[:error] = "There was an error creating the record. Please try again."
      render new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
    @disable_search = true
  end

  def update
    @venue = Venue.find(params[:id])
    @venue.update_attributes(venue_params)


    if @venue.save
      flash[:notice] = "Venue updated."
      redirect_to admin_venue_path(@venue)
    else
      flash[:error] = "There was an error saving the changes. Please try again."
      render :edit
    end

  end


  def destroy
    @venue = Venue.find(params[:id])

    if @venue.destroy
      flash[:notice] = "\"#{@venue.name}\" was deleted successfully."
      redirect_to admin_venues_path
    else
      flash[:error] = "There was an error deleting the Venue."
      render :show
    end
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address, :latitude, :longitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
      @venues = Venue.has_address
      @tradeshows = Tradeshow.all.order("date DESC").paginate(page: params[:page], per_page: 5)
        if params[:search]
          @tradeshows = Tradeshow.search(params[:search]).order("date DESC").paginate(page: params[:page], per_page: 5)
        else
          @tradeshows = Tradeshow.all.order("date DESC").paginate(page: params[:page], per_page: 5)
        end

      @hash = Gmaps4rails.build_markers(@venues) do |venue, marker|
        info_window = "#{venue.address}"
        marker.lat venue.latitude
        marker.lng venue.longitude
        marker.infowindow info_window
        marker.json({:id => venue.id})
      #   marker.picture({
      #     "url" => "#{}",
      #     "width" =>  "36",
      #     "height" => "36"
      # })
      end
  end
end

app/helpers/admin/tradeshows_helper.rb
module Admin::TradeshowsHelper
end

app/helpers/admin/venues_helper.rb
module Admin::VenuesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/admin/show.html.erb
<h1>This is the admin show page.</h1>
<div class="container">
  <div class="row">
    <p>
      <%= link_to "All Venues", admin_venues_path %>
    </p>
    <p>
      <%= link_to "New Venue", new_admin_venue_path %>
    </p>
  </div>
  <div class="row">
    <p>
      <%= link_to "All TradeShows", admin_tradeshows_path %>
    </p>
    <p>
      <%= link_to "New Tradeshow", new_admin_tradeshow_path %>
    </p>
  </div>
</div>

app/views/admin/tradeshows/_booth_fields.html.erb
  <%= f.fields_for :booths do |booth_form| %>
    <ul>
      <div class="booth-form-group">
        <li class="booth-form">
          <%= booth_form.number_field :size, placeholder: "Size" %>
        </li>
      </div>
    </ul>
  <% end %>

app/views/admin/tradeshows/edit.html.haml
.container
  %h1
    ="#{@tradeshow.title}"
  .form-title Edit TradeShow
  %br/
  .form
    .form-group-columns
      =form_for [:admin, @tradeshow]  do |f|
        = f.text_field :title, placeholder: "Title"
        %br/
        %br/
        = f.text_area :description, placeholder: "Description"
        %br/
        = f.text_field :location, placeholder: "Address"
        %br/
        = f.date_select(:date , :start_year => 2016)
        %br/
        %br/
        = f.submit "Update", class: "button"

app/views/admin/tradeshows/index.html.haml
-@tradeshows.each do |tradeshow|
  = tradeshow.title
  = tradeshow.description
  = tradeshow.location
  = tradeshow.date

app/views/admin/tradeshows/new.html.erb
<div class="container">
  <div class="form-title">New TradeShow</div>
  <br/>
  <div class="form">
    <div class="form-group-columns">
      <%= form_for [:admin, @tradeshow] do |f| %>
        <%= f.text_field :title, placeholder: "Title" %>
        <br/>
        <br/>
        <%= f.text_area :description, placeholder: "Description" %>

        <br/>
        <br/>
        <%= f.text_field :venue_name, placeholder: "Venue" %>
        <br/>
        <%= f.text_field :location, placeholder: "Address" %>
        <br/>

        <%= f.date_select(:date , :start_year => 2016) %>
        <br/>
        <br/>

          <%= f.fields_for :booths, Booth.new do |booth_form| %>
          <div class="booth-form-group">
              <!-- Done in JS right now tradeshow.js -->
            </div>
          <% end %>

          <%#= render partial: "booth_fields", locals: {f: f} %>
          <%= link_to "", "#", id: :booth_add, class: "fa-1.5x fa fa-plus-circle booth-form-add" %>
          <br/>
          <br/>

          <div class="spacer"></div>
        <%= f.submit :save, class: "button" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/tradeshows/show.html.erb
<div class="container">
  <h1>this is the show view!</h1>
  <div class="row">
    <div class="column fourth">
      <p>Title:</p><%= @tradeshow.title %>
    </div>
    <div class="column fourth">
      <p>Description:</p><%= @tradeshow.description %>
    </div>
    <div class="column fourth">
      <p>Date:</p><%= @tradeshow.date %>
    </div>
    <div class="column fourth">
      <p>Location:</p><%= @tradeshow.location %>
    </div>
  </div>
  <div class="tradeshow-booths column fourth">
    <p>Booth: </p>
    <% @tradeshow.booths.each do |booth| %>
      <%= "#{booth.size} Sq. Feet" %>
      <% end %>
  </div>
</div>

<div class="spacer-xl"></div>
<div class="container stacking">
  <div class="row">
    <div class="column fourth">
      <%= link_to "Edit", edit_admin_tradeshow_path(@tradeshow), class: "button" %>
    </div>
    <div class="column fourth">
      <%= link_to "Delete", admin_tradeshow_path(@tradeshow), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "button button-delete" %>
    </div>
  </div>
</div>

app/views/admin/venues/edit.html.haml
.container
  .form-title Edit Venue
  %br/
  .form
    .form-group-columns
      =form_for [:admin, @venue]  do |f|
        = f.text_field :name, placeholder: "Name"
        %br/
        %br/
        = f.text_field :address, placeholder: "Address"
        %br/
        %br/
        = f.submit "Update", class: "button"

app/views/admin/venues/index.html.erb
<div class="container">
  <ul>
    <% @venues.each do |venue| %>
      <li>
        <%= venue.name %>
        <%= venue.address %>
        <%= venue.longitude %>
        <%= venue.latitude %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/venues/new.html.haml
.container
  .form-title New Venue
  %br/
  .form
    .form-group-columns
      =form_for [:admin, @venue]  do |f|
        = f.text_field :name, placeholder: "Name"
        %br/
        %br/
        = f.text_field :address, placeholder: "Address"
        %br/
        %br/
        = f.submit :save, class: "button"

app/views/admin/venues/show.html.haml
%h1 this is the show view!
.container
  .row
    .column.fourth
      %p Name:
      = @venue.name
    .column.fourth
      %p Address:
      = @venue.address
    .column.fourth
      %p Latitude:
      = @venue.latitude
    .column.fourth
      %p Longitude:
      = @venue.longitude
.spacer-xl
.container.stacking
  .row
    .column.fourth
      = link_to "Edit", edit_admin_venue_path(@venue), class: "button"
    .column.fourth
      = link_to "Delete", admin_venue_path(@venue), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "button button-delete"

app/views/layouts/_flash.html.haml
.flash
  - if flash[:notice]
    .alert.alert-success
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:notice]
  - elsif flash[:error]
    .alert.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:error]
  - elsif flash[:alert]
    .alert.alert-warning
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      = flash[:alert]
      

app/views/layouts/_nav.html.haml
%nav.navbar
  .links-container
    %a.navbar-link
      = render partial: "layouts/search_form" unless @disable_search
    %a.navbar-link{:href => root_path} TradeShowMarket
    %a.navbar-link{:href => new_admin_session_path} Admin

app/views/layouts/_search_form.html.erb
<%= form_tag(public_index_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], class: "input-search", placeholder: "Search Tradeshows" %>
  <%= submit_tag "Search", class: "submit-search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MarketplaceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel="stylesheet" type="text/css"></link>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <!-- <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> -->
</head>
<body>
<%= render 'layouts/flash' %>
<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>